source "https://rubygems.org"

gemspec

# Exclude development-only gems from dependabot.
unless ENV["DEPENDABOT"]
  gem "dotenv"

  gem "rake"
  gem "rspec", "~> 3.11"

  # Exclude development-only gems from the gemfiles generated by appraisal.
  unless defined?(::Appraisal::Gemfile) && is_a?(::Appraisal::Gemfile)
    gem "standard", "~> 1.0"
    gem "simplecov", "~> 1.0", require: false
    gem "yard"
  end
end
